package io.solar.entity.messenger;

public enum NotificationType {
    INVITED_TO_ROOM,
    EDITED_ROOM_TITLE,
    BET_OVERBID,
    INSTANT_PURCHASE,
    MONEY_UPDATED,
    LEAVE_ROOM,
    EXCHANGE_INVITATION,
    EXCHANGE_CREATED,
    EXCHANGE_INVITATION_REJECTED,
    MESSAGE_TO_SCREEN
}
