package io.solar.entity.messenger;

public enum NotificationType {
    INVITED_TO_ROOM,
    EDITED_ROOM_TITLE,
    BET_OVERBID,
    INSTANT_PURCHASE,
    MONEY_UPDATED,
    LEAVE_ROOM,
    MESSAGE_TO_SCREEN,
    EXCHANGE_INVITATION,
    EXCHANGE_INVITATION_REJECTED,
    EXCHANGE_CREATED,
    LEAVE_EXCHANGE,
    OFFER_CREATED,
    OFFER_UPDATED,
}
