package io.solar.entity.messenger;

public enum NotificationType {
    INVITED_TO_ROOM,
    EDITED_ROOM_TITLE,
    KICK_OR_LEAVE_USER_FROM_ROOM,

    ROOM_DELETED,
    BET_OVERBID,
    INSTANT_PURCHASE,
    MONEY_UPDATED,
    MESSAGE_TO_SCREEN,
    EXCHANGE_INVITATION,
    EXCHANGE_INVITATION_REJECTED,
    EXCHANGE_CREATED,
    EXCHANGE_COMPLETED,
    LEAVE_EXCHANGE,
    OFFER_CREATED,
    OFFER_UPDATED,
    CANNOT_ATTACH_TO_ORBIT
}
