spring:
    mvc:
        log-resolved-exception: true

    datasource:
        url: ${solar_db_url}
        driver-class-name: org.mariadb.jdbc.Driver
        username: ${solar_db_user}
        password: ${solar_db_pass}
        hikari:
            minimum-idle: 10
            maximum-pool-size: 50

    flyway:
        url: ${solar_db_url}
        user: ${solar_db_user}
        password: ${solar_db_pass}
        encoding: UTF-8
        out-of-order: true
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0

    jpa:
        properties:
            hibernate:
                show_sql: false
                format_sql: true
                use_sql_comments: false
                ddl-auto: validate
        open-in-view: false

    mail:
        host: smtp.gmail.com
        port: 587
        username: solar.super.game@gmail.com
        password: verystrongpass
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
    port: 8081
    servlet:
        encoding:
            charset: UTF-8

app:
    jwt_secret: ${solar_token_secret}
    token_lifetime_min: 30
    hack_block_time_min: 5
    admin_not_exists: "yes"
    goods_generation_delay_minutes: 60
    goods_initial_delay_minutes: 60
    view_distance_without_radar: 5
    time_flow_modifier: 12
    station_sell_modifier: 0.7

    images:
        path: src/main/resources/images
        width: 300
        height: 300
    navigator:
        max_distance: 10
        max_speed: 1000
        update_coordinates_delay: PT15M
        num_update_object: 100
    email:
        token_lifetime_hours: 24
        forgot_password_template: http://localhost:8081/forgot-password.html?token=
    marketplace:
        bet_step_percents: 2
        commission_percent: 5
    messenger:
        notification_destination: "/notifications"
    star_map:
        capture_distance: 100
    object:
        types:
            radar: radar
            container: container
            engine: engine
            huge_engine: huge_engine
            generator: generator
            large_generator: large_generator
            battery: battery
    star_ship:
        drop_radius: 10


log4jdbc:
    dump:
        sql:
            maxlinelength: 90
            addsemicolon: true
    trim:
        sql:
            extrablanklines: true

logging:
    level:
        jdbc:
            sqlonly: "OFF"
            sqltiming: "OFF"
            audit: "OFF"
            resultset: "OFF"
            resultsettable: "OFF"
            connection: "OFF"