spring:
  datasource:
    url: jdbc:mariadb://localhost/solar?useSSL=false&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${solar_db_user}
    password: ${solar_db_pass}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  flyway:
    url: jdbc:mariadb://localhost/solar?useSSL=false&serverTimezone=UTC
    user: ${solar_db_user}
    password: ${solar_db_pass}
    encoding: UTF-8
    out-of-order: true
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: validate
    open-in-view: false

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8

app:
  jwt_secret: ${solar_token_secret}
  token_lifetime_min: 30
  hack_block_time_min: 5
  admin_not_exists: "yes"
  goods_generation_delay_minutes: 60
  goods_initial_delay_minutes: 60