
spring:
  datasource:
    url: jdbc:mysql://localhost/solar?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${solar_db_user}
    password: ${solar_db_pass}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50


  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect

  thymeleaf:
    encoding: UTF-8
    suffix: .html
    prefix: /templates/